### ISSUE TITLE
Anmeldung nicht möglich

### ISSUE THREAD

**Issue by 123gerald1** [s10l/dbus-deye-sun-g3-pvinverter#1]
Hallo,
Ich versuche gerade den Adapter für den Deye Michrowechselrichter zu installieren, leider bekomme ich es nicht hin.
Wo muss ich den username und das passwort eintragen?
Sg. Gerald

**Comment by s10l** [comment]
Username und Password vom Wechselrichter wird nicht benötigt, die Daten werden über den Solarman V5 Port (8899) gezogen.
