### ISSUE TITLE
Findet Datei install.sh nicht

### ISSUE THREAD

**Issue by radballer** [s10l/dbus-deye-sun-g3-pvinverter#2]
moin s10l

ich habe dein Programm jetzt Installieren können. 
Leider Funktioniert es nicht so wie ich es gerne hätte. 

Schreib mir bitte, dann könnte ich dir das Problem direkt zeigen mittelts TeamViewer oder ähnlichem. 

Grüße Christian

**Comment by s10l** [comment]
Bis zu welchem Schritt kommst du?
c&p gerne deine Eingaben und die Ausgabe vom Prompt.

**Comment by s10l** [comment]
Ich habe auch einen Abschnitt zum Testen der Konfiguration hinzugefügt:
https://github.com/s10l/dbus-deye-sun-g3-pvinverter#testing-configuration
