### ISSUE TITLE
run file not in directory service

### ISSUE THREAD

**Issue by EntwicklungScuddy** [s10l/dbus-deye-sun-g3-pvinverter#4]
Hi. I had some isues installiung the service. It was mainly because after downloading, like described in the manual, the " run " file is not in the directory " service ". I needed to mkdir the directrory and copy the file into it.

I have two 600 inverters. so I duplicated the main directroy into /data/dbus-deye-sun-g3-pvinverter2/ and configurated it into instance 42 . It works fine :-)
Is duplicating the desired way?

**Comment by s10l** [comment]
**run file not found**
thanks for reporting, fixed the issue.


**multiple device support**
Would be awesome to support multiple devices.

To be honest, this solution is not used very often. I guess most users use a shelly to measure power output.

For one device it works perfect, for multiple devices there is your workaround.
Many thanks for that too. I will include it in the instructions.

If you want to implement the multi-device support, I can certainly support you.
